apiVersion: v1
kind: Service
metadata:
  name: unified-documents-api
  namespace: keyloop
  labels:
    app.kubernetes.io/name: unified-documents
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: unified-documents
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP